name: Prepare Database

on:
  push:
    branches:
      - deploy

jobs:
  "setup-database":
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Delete old database
        run: npm run remove-db

      - name: Seed database
        run: npm insert-sample-db
